# -*- coding: utf-8 -*-
"""Assignment_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dtrtf064DzHYws9vgrLkR3JGSG5yn75F

Q.1. Create two int type variables, apply addition, subtraction, division
and multiplications and store the results in variables. Then print the
data in the following format by calling the variables:
First variable is __ & second variable is __.
Addition: __ + __ = __
Subtraction: __ - __ = __
Multiplication: __ * __ = __
Division: __ / __ = __
Ans:
num1 = int(input("Enter first number"))
num2 = int(input("Enter Second number"))
print(f"First variable is {num1} & second variable is {num2}.")
sum=num1+num2
print(f"Addition: {num1} + {num2} = {sum}")
diff=num1-num2
print(f"Subtraction: {num1} - {num2} = {diff}")
mul=num1*num2
print(f"Multiplication: {num1} * {num2} = {mul}")
if num2 != 0 :
   div = num1/num2
   print(f"Division: {num1} / {num2} = {div} ")
else: print("divide by 0 not possible")


Q.2. What is the difference between the following operators:
(i) ‘/’ & ‘//’
/ will give a float value ex:- 1.2 , 0.2 , etc.,
// will give only the integer part of quotient (i.e., 3.2 will be 3) and it
is a floor division

(ii) ‘**’ & ‘^’
** is an exponetial operator
^ is a bitwise operator XOR

Q.3. List the logical operators.
Ans: and, or, not are the logical operators

Q.4. Explain right shift operator and left shift operator with examples
Ans:
>> is a right shift operator it shifts the bit value of a given number by
specified times.
ex:- 5>>2 is 1 because 5 in binary 101 if shifted right 2 times only 1 remains

<< is a left shift operator it shifts the bit value of a given number by specified  times.
ex:- 5<< 2 is 20 because binary 101 now becomes 10100  


Q.5. Create a list containing int type data of length 15. Then write a
code to check if 10 is present in the list or not.
Ans:
l=[]
for i in range(15):
  l.append(i)

if 10 in l:
  print("10 is present in list")
else : print("10 is not in the list")
"""